CREATE DATABASE IF NOT EXISTS SOAPSERVER;

USE SOAPSERVER;

CREATE TABLE IF NOT EXISTS ARTICLES (
    ARTICLES_ID bigint(5) NOT NULL AUTO_INCREMENT,
    TITLE varchar(200) NOT NULL,
    CATEGORY varchar(100) NOT NULL,
    PRIMARY KEY (ARTICLES_ID)) ENGINE=InnoDB;

INSERT INTO ARTICLES (ARTICLES_ID, TITLE, CATEGORY)
VALUES
(1, 'Java Concurrency', 'Java'),
(2, 'Spring Boot Getting Started', 'Spring Boot');